<a href="https://colab.research.google.com/github/srilakshmi-saladi/bdaassignment/blob/main/linearalgebranumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr = np.random.randint(1, 21, size=15)

reshaped_arr = arr.reshape(3, 5)


print("Shape of array:", reshaped_arr.shape)

print("Shape of array Before:", reshaped_arr)

for i in range(reshaped_arr.shape[0]):
    max_index = reshaped_arr[i].argmax()
    reshaped_arr[i, max_index] = 0

print("Modified array:\n", reshaped_arr)


Shape of array: (3, 5)
Shape of array Before: [[ 1  7  6 13  4]
 [12  2 20  2 16]
 [15 17  6  5 11]]
Modified array:
 [[ 1  7  6  0  4]
 [12  2  0  2 16]
 [15  0  6  5 11]]


In [4]:
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)


print("Array:\n", arr)


print("Shape:", arr.shape)

print("Type:", type(arr))
print("Data type:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [5]:
import numpy as np


A = np.array([[3, -2],
              [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(A)


print("Eigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [6]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5]])


diag_sum = np.trace(arr)

print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [7]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print("Original array (3x2):")
print(arr)


reshaped_arr = arr.reshape(2, 3)

print("\nReshaped array (2x3):")
print(reshaped_arr)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
